# Set the build Linux distribution
dist:                     xenial

# Set the build language
language:                 generic

before_install:
  # Configure access token to enable pushing to the repository
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Quick-Scan.git

  # Set commit username
  - git config --global user.name "ROS Bot"

  # Set commit email
  - git config --global user.email "richiebendall@gmail.com"

before_script:
  # Delete the old hashes file
  - rm -f ROSQuickScanLibrary.txt

script:
  # Download the new hashes file
  - curl -L -o ROSQuickScanLibrary.txt https://raw.githack.com/Richienb/virusshare-hashes/master/virushashes.txt
  
after_script:
  # Add file to the cache
  - git add ROSQuickScanLibrary.txt
  
  # Commit file
  - git commit -m "CI | Updated the hashes library for legacy support [skip ci]"
  
  # Push the commit
  - git push

# Disable emails for build status notifications
notifications: email:     false
